apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: slneo/multi-client
      context: complex/client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: slneo/multi-server
      context: complex/server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: slneo/multi-worker
      context: complex/worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
deploy:
  kubectl:
    manifests:
      - complex/k8s/client-deployment.yaml
      - complex/k8s/server-deployment.yaml
      - complex/k8s/worker-deployment.yaml
